# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSwatch',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='styleguide_colorswatch', serialize=False, to='cms.CMSPlugin')),
                ('color', models.CharField(default='343434', max_length=6)),
                ('name', models.CharField(default='new color', max_length=20)),
                ('sass_name', models.CharField(default='$newColor', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
