# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('styleguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexContainer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='styleguide_flexcontainer', serialize=False, to='cms.CMSPlugin')),
                ('spacing', models.CharField(choices=[('flex-start', 'flex-start'), ('flex-end', 'flex-end'), ('center', 'center'), ('space-between', 'space-between'), ('space-around', 'space-around')], default='space-around', max_length=13)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
