# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleguide', '0003_auto_20180627_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='background_color',
            field=models.CharField(choices=[('#1c2532', 'navy'), ('#f3f4f5', 'light'), ('#ffffff', 'white')], default='white', max_length=20),
        ),
    ]
