# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('styleguide', '0005_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterBox',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='styleguide_newsletterbox', serialize=False, to='cms.CMSPlugin')),
                ('call_to_action', models.CharField(default='', max_length=140)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
