# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
        ('styleguide', '0006_newsletterbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTile',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='styleguide_applicationtile', serialize=False, to='cms.CMSPlugin')),
                ('app_name', models.CharField(default='Cell Types Database', max_length=50)),
                ('app_description', models.CharField(default='This section contains description copy for this Atlas or Database.', max_length=140)),
                ('app_url', models.CharField(default='http://celltypes.brain-map.org/', max_length=1000)),
                ('app_thumbnail', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_thumbnail', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
