# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('styleguide', '0007_applicationtile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypographicSample',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='styleguide_typographicsample', serialize=False, to='cms.CMSPlugin')),
                ('font_family', models.CharField(choices=[('avenir-next', 'Avenir Next'), ('roboto', 'Roboto')], default='Roboto', max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
