# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('styleguide', '0008_typographicsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexColumn',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='styleguide_flexcolumn', serialize=False, to='cms.CMSPlugin')),
                ('column_width', models.CharField(choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('80%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], default='50%', max_length=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='flexcontainer',
            name='direction',
            field=models.CharField(choices=[('row', 'Row'), ('row-reverse', 'Row Reverse'), ('column', 'Column'), ('column-reverse', 'Column Reverse')], default='row', max_length=20),
        ),
        migrations.AddField(
            model_name='flexcontainer',
            name='wrap',
            field=models.CharField(choices=[('wrap', 'Wrap'), ('nowrap', 'No Wrap'), ('wrao-reverse', 'Wrap Reverse')], default='wrap', max_length=20),
        ),
    ]
