# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('styleguide', '0009_auto_20180710_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='styleguide_button', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(default='Click Me!', max_length=140)),
                ('url', models.CharField(default='#', max_length=2000)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black')], default='Blue', max_length=25)),
                ('style', models.CharField(choices=[('primary', 'Primary Button'), ('secondary', 'Secondary Button'), ('compact', 'Compact Button'), ('text', 'Small Link')], default='Primary Button', max_length=25)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
